//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;
using System.Globalization;
using System.Linq;
using JetBrains.Annotations;
using UnitsNet.InternalHelpers;
using UnitsNet.Units;
using UnitsNet;
using UnitsNetQuantityExtensionExample.Custom.Units;


// ReSharper disable once CheckNamespace

namespace   .Custom.Quantities
{
    /// <inheritdoc />
    /// <summary>
    ///     Derived quantity from length. Vertical distance below a surface.
    /// </summary>
    public partial struct Depth : IQuantity<DepthUnit>, IEquatable<Depth>, IComparable, IComparable<Depth>, IConvertible, IFormattable
    {
        /// <summary>
        ///     The numeric value this quantity was constructed with.
        /// </summary>
        private readonly double _value;

        /// <summary>
        ///     The unit this quantity was constructed with.
        /// </summary>
        private readonly DepthUnit? _unit;

        static Depth()
        {
            BaseDimensions = new BaseDimensions(1, 0, 0, 0, 0, 0, 0);

            Info = new QuantityInfo<DepthUnit>("Depth",
                new UnitInfo<DepthUnit>[] {
                    new UnitInfo<DepthUnit>(DepthUnit.Centimeter, BaseUnits.Undefined),
                    new UnitInfo<DepthUnit>(DepthUnit.Decimeter, BaseUnits.Undefined),
                    new UnitInfo<DepthUnit>(DepthUnit.Foot, new BaseUnits(length: LengthUnit.Foot)),
                    new UnitInfo<DepthUnit>(DepthUnit.Hectometer, BaseUnits.Undefined),
                    new UnitInfo<DepthUnit>(DepthUnit.Inch, new BaseUnits(length: LengthUnit.Inch)),
                    new UnitInfo<DepthUnit>(DepthUnit.Kilometer, BaseUnits.Undefined),
                    new UnitInfo<DepthUnit>(DepthUnit.Meter, new BaseUnits(length: LengthUnit.Meter)),
                    new UnitInfo<DepthUnit>(DepthUnit.Micrometer, BaseUnits.Undefined),
                    new UnitInfo<DepthUnit>(DepthUnit.Mil, new BaseUnits(length: LengthUnit.Mil)),
                    new UnitInfo<DepthUnit>(DepthUnit.Mile, new BaseUnits(length: LengthUnit.Mile)),
                    new UnitInfo<DepthUnit>(DepthUnit.Millimeter, BaseUnits.Undefined),
                    new UnitInfo<DepthUnit>(DepthUnit.Nanometer, BaseUnits.Undefined),
                    new UnitInfo<DepthUnit>(DepthUnit.UsSurveyFoot, new BaseUnits(length: LengthUnit.UsSurveyFoot)),
                    new UnitInfo<DepthUnit>(DepthUnit.Yard, new BaseUnits(length: LengthUnit.Yard)),
                },
                BaseUnit, Zero, BaseDimensions);
        }

        /// <summary>
        ///     Creates the quantity with the given numeric value and unit.
        /// </summary>
        /// <param name="value">The numeric value to construct this quantity with.</param>
        /// <param name="unit">The unit representation to construct this quantity with.</param>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public Depth(double value, DepthUnit unit)
        {
            if(unit == DepthUnit.Undefined)
              throw new ArgumentException("The quantity can not be created with an undefined unit.", nameof(unit));

            _value = Guard.EnsureValidNumber(value, nameof(value));
            _unit = unit;
        }

        /// <summary>
        /// Creates an instance of the quantity with the given numeric value in units compatible with the given <see cref="UnitSystem"/>.
        /// If multiple compatible units were found, the first match is used.
        /// </summary>
        /// <param name="value">The numeric value to construct this quantity with.</param>
        /// <param name="unitSystem">The unit system to create the quantity with.</param>
        /// <exception cref="ArgumentNullException">The given <see cref="UnitSystem"/> is null.</exception>
        /// <exception cref="ArgumentException">No unit was found for the given <see cref="UnitSystem"/>.</exception>
        public Depth(double value, UnitSystem unitSystem)
        {
            if(unitSystem is null) throw new ArgumentNullException(nameof(unitSystem));

            var unitInfos = Info.GetUnitInfosFor(unitSystem.BaseUnits);
            var firstUnitInfo = unitInfos.FirstOrDefault();

            _value = Guard.EnsureValidNumber(value, nameof(value));
            _unit = firstUnitInfo?.Value ?? throw new ArgumentException("No units were found for the given UnitSystem.", nameof(unitSystem));
        }

        #region Static Properties

        /// <inheritdoc cref="IQuantity.QuantityInfo"/>
        public static QuantityInfo<DepthUnit> Info { get; }

        /// <summary>
        ///     The <see cref="BaseDimensions" /> of this quantity.
        /// </summary>
        public static BaseDimensions BaseDimensions { get; }

        /// <summary>
        ///     The base unit of Depth, which is Meter. All conversions go via this value.
        /// </summary>
        public static DepthUnit BaseUnit { get; } = DepthUnit.Meter;

        /// <summary>
        /// Represents the largest possible value of Depth
        /// </summary>
        [Obsolete("MaxValue and MinValue will be removed. Choose your own value or use nullability for unbounded lower/upper range checks. See discussion in https://github.com/angularsen/UnitsNet/issues/848.")]
        public static Depth MaxValue { get; } = new Depth(double.MaxValue, BaseUnit);

        /// <summary>
        /// Represents the smallest possible value of Depth
        /// </summary>
        [Obsolete("MaxValue and MinValue will be removed. Choose your own value or use nullability for unbounded lower/upper range checks. See discussion in https://github.com/angularsen/UnitsNet/issues/848.")]
        public static Depth MinValue { get; } = new Depth(double.MinValue, BaseUnit);

        /// <summary>
        ///     The <see cref="QuantityType" /> of this quantity.
        /// </summary>
        [Obsolete("QuantityType will be removed in the future. Use Info property instead.")]
        public static QuantityType QuantityType { get; } = QuantityType.Undefined;

        /// <summary>
        ///     All units of measurement for the Depth quantity.
        /// </summary>
        public static DepthUnit[] Units { get; } = Enum.GetValues(typeof(DepthUnit)).Cast<DepthUnit>().Except(new DepthUnit[]{ DepthUnit.Undefined }).ToArray();

        /// <summary>
        ///     Gets an instance of this quantity with a value of 0 in the base unit Meter.
        /// </summary>
        public static Depth Zero { get; } = new Depth(0, BaseUnit);

        #endregion

        #region Properties

        /// <summary>
        ///     The numeric value this quantity was constructed with.
        /// </summary>
        public double Value => _value;

        Enum IQuantity.Unit => Unit;

        /// <inheritdoc />
        public DepthUnit Unit => _unit.GetValueOrDefault(BaseUnit);

        /// <inheritdoc />
        public QuantityInfo<DepthUnit> QuantityInfo => Info;

        /// <inheritdoc cref="IQuantity.QuantityInfo"/>
        QuantityInfo IQuantity.QuantityInfo => Info;

        /// <summary>
        ///     The <see cref="QuantityType" /> of this quantity.
        /// </summary>
        public QuantityType Type => QuantityType.Undefined;

        /// <summary>
        ///     The <see cref="BaseDimensions" /> of this quantity.
        /// </summary>
        public BaseDimensions Dimensions => Depth.BaseDimensions;

        #endregion

        #region Conversion Properties

        /// <summary>
        ///     Get Depth in Centimeters.
        /// </summary>
        public double Centimeters => As(DepthUnit.Centimeter);

        /// <summary>
        ///     Get Depth in Decimeters.
        /// </summary>
        public double Decimeters => As(DepthUnit.Decimeter);

        /// <summary>
        ///     Get Depth in Feet.
        /// </summary>
        public double Feet => As(DepthUnit.Foot);

        /// <summary>
        ///     Get Depth in Hectometers.
        /// </summary>
        public double Hectometers => As(DepthUnit.Hectometer);

        /// <summary>
        ///     Get Depth in Inches.
        /// </summary>
        public double Inches => As(DepthUnit.Inch);

        /// <summary>
        ///     Get Depth in Kilometers.
        /// </summary>
        public double Kilometers => As(DepthUnit.Kilometer);

        /// <summary>
        ///     Get Depth in Meters.
        /// </summary>
        public double Meters => As(DepthUnit.Meter);

        /// <summary>
        ///     Get Depth in Micrometers.
        /// </summary>
        public double Micrometers => As(DepthUnit.Micrometer);

        /// <summary>
        ///     Get Depth in Mils.
        /// </summary>
        public double Mils => As(DepthUnit.Mil);

        /// <summary>
        ///     Get Depth in Miles.
        /// </summary>
        public double Miles => As(DepthUnit.Mile);

        /// <summary>
        ///     Get Depth in Millimeters.
        /// </summary>
        public double Millimeters => As(DepthUnit.Millimeter);

        /// <summary>
        ///     Get Depth in Nanometers.
        /// </summary>
        public double Nanometers => As(DepthUnit.Nanometer);

        /// <summary>
        ///     Get Depth in UsSurveyFeet.
        /// </summary>
        public double UsSurveyFeet => As(DepthUnit.UsSurveyFoot);

        /// <summary>
        ///     Get Depth in Yards.
        /// </summary>
        public double Yards => As(DepthUnit.Yard);

        #endregion

        #region Static Methods

        /// <summary>
        ///     Get unit abbreviation string.
        /// </summary>
        /// <param name="unit">Unit to get abbreviation for.</param>
        /// <returns>Unit abbreviation string.</returns>
        public static string GetAbbreviation(DepthUnit unit)
        {
            return GetAbbreviation(unit, null);
        }

        /// <summary>
        ///     Get unit abbreviation string.
        /// </summary>
        /// <param name="unit">Unit to get abbreviation for.</param>
        /// <returns>Unit abbreviation string.</returns>
        /// <param name="provider">Format to use for localization. Defaults to <see cref="CultureInfo.CurrentUICulture" /> if null.</param>
        public static string GetAbbreviation(DepthUnit unit, IFormatProvider provider)
        {
            return UnitAbbreviationsCache.Default.GetDefaultAbbreviation(unit, provider);
        }

        #endregion

        #region Static Factory Methods

        /// <summary>
        ///     Get Depth from Centimeters.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static Depth FromCentimeters(QuantityValue centimeters)
        {
            double value = (double) centimeters;
            return new Depth(value, DepthUnit.Centimeter);
        }
        /// <summary>
        ///     Get Depth from Decimeters.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static Depth FromDecimeters(QuantityValue decimeters)
        {
            double value = (double) decimeters;
            return new Depth(value, DepthUnit.Decimeter);
        }
        /// <summary>
        ///     Get Depth from Feet.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static Depth FromFeet(QuantityValue feet)
        {
            double value = (double) feet;
            return new Depth(value, DepthUnit.Foot);
        }
        /// <summary>
        ///     Get Depth from Hectometers.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static Depth FromHectometers(QuantityValue hectometers)
        {
            double value = (double) hectometers;
            return new Depth(value, DepthUnit.Hectometer);
        }
        /// <summary>
        ///     Get Depth from Inches.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static Depth FromInches(QuantityValue inches)
        {
            double value = (double) inches;
            return new Depth(value, DepthUnit.Inch);
        }
        /// <summary>
        ///     Get Depth from Kilometers.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static Depth FromKilometers(QuantityValue kilometers)
        {
            double value = (double) kilometers;
            return new Depth(value, DepthUnit.Kilometer);
        }
        /// <summary>
        ///     Get Depth from Meters.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static Depth FromMeters(QuantityValue meters)
        {
            double value = (double) meters;
            return new Depth(value, DepthUnit.Meter);
        }
        /// <summary>
        ///     Get Depth from Micrometers.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static Depth FromMicrometers(QuantityValue micrometers)
        {
            double value = (double) micrometers;
            return new Depth(value, DepthUnit.Micrometer);
        }
        /// <summary>
        ///     Get Depth from Mils.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static Depth FromMils(QuantityValue mils)
        {
            double value = (double) mils;
            return new Depth(value, DepthUnit.Mil);
        }
        /// <summary>
        ///     Get Depth from Miles.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static Depth FromMiles(QuantityValue miles)
        {
            double value = (double) miles;
            return new Depth(value, DepthUnit.Mile);
        }
        /// <summary>
        ///     Get Depth from Millimeters.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static Depth FromMillimeters(QuantityValue millimeters)
        {
            double value = (double) millimeters;
            return new Depth(value, DepthUnit.Millimeter);
        }
        /// <summary>
        ///     Get Depth from Nanometers.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static Depth FromNanometers(QuantityValue nanometers)
        {
            double value = (double) nanometers;
            return new Depth(value, DepthUnit.Nanometer);
        }
        /// <summary>
        ///     Get Depth from UsSurveyFeet.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static Depth FromUsSurveyFeet(QuantityValue ussurveyfeet)
        {
            double value = (double) ussurveyfeet;
            return new Depth(value, DepthUnit.UsSurveyFoot);
        }
        /// <summary>
        ///     Get Depth from Yards.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static Depth FromYards(QuantityValue yards)
        {
            double value = (double) yards;
            return new Depth(value, DepthUnit.Yard);
        }

        /// <summary>
        ///     Dynamically convert from value and unit enum <see cref="DepthUnit" /> to <see cref="Depth" />.
        /// </summary>
        /// <param name="value">Value to convert from.</param>
        /// <param name="fromUnit">Unit to convert from.</param>
        /// <returns>Depth unit value.</returns>
        public static Depth From(QuantityValue value, DepthUnit fromUnit)
        {
            return new Depth((double)value, fromUnit);
        }

        #endregion

        #region Static Parse Methods

        /// <summary>
        ///     Parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.Parse("5.5 m", new CultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="ArgumentException">
        ///     Expected string to have one or two pairs of quantity and unit in the format
        ///     "&lt;quantity&gt; &lt;unit&gt;". Eg. "5.5 m" or "1ft 2in"
        /// </exception>
        /// <exception cref="AmbiguousUnitParseException">
        ///     More than one unit is represented by the specified unit abbreviation.
        ///     Example: Volume.Parse("1 cup") will throw, because it can refer to any of
        ///     <see cref="VolumeUnit.MetricCup" />, <see cref="VolumeUnit.UsLegalCup" /> and <see cref="VolumeUnit.UsCustomaryCup" />.
        /// </exception>
        /// <exception cref="UnitsNetException">
        ///     If anything else goes wrong, typically due to a bug or unhandled case.
        ///     We wrap exceptions in <see cref="UnitsNetException" /> to allow you to distinguish
        ///     Units.NET exceptions from other exceptions.
        /// </exception>
        public static Depth Parse(string str)
        {
            return Parse(str, null);
        }

        /// <summary>
        ///     Parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.Parse("5.5 m", new CultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="ArgumentException">
        ///     Expected string to have one or two pairs of quantity and unit in the format
        ///     "&lt;quantity&gt; &lt;unit&gt;". Eg. "5.5 m" or "1ft 2in"
        /// </exception>
        /// <exception cref="AmbiguousUnitParseException">
        ///     More than one unit is represented by the specified unit abbreviation.
        ///     Example: Volume.Parse("1 cup") will throw, because it can refer to any of
        ///     <see cref="VolumeUnit.MetricCup" />, <see cref="VolumeUnit.UsLegalCup" /> and <see cref="VolumeUnit.UsCustomaryCup" />.
        /// </exception>
        /// <exception cref="UnitsNetException">
        ///     If anything else goes wrong, typically due to a bug or unhandled case.
        ///     We wrap exceptions in <see cref="UnitsNetException" /> to allow you to distinguish
        ///     Units.NET exceptions from other exceptions.
        /// </exception>
        /// <param name="provider">Format to use when parsing number and unit. Defaults to <see cref="CultureInfo.CurrentUICulture" /> if null.</param>
        public static Depth Parse(string str, IFormatProvider provider)
        {
            return QuantityParser.Default.Parse<Depth, DepthUnit>(
                str,
                provider,
                From);
        }

        /// <summary>
        ///     Try to parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="result">Resulting unit quantity if successful.</param>
        /// <example>
        ///     Length.Parse("5.5 m", new CultureInfo("en-US"));
        /// </example>
        public static bool TryParse(string str, out Depth result)
        {
            return TryParse(str, null, out result);
        }

        /// <summary>
        ///     Try to parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="result">Resulting unit quantity if successful.</param>
        /// <returns>True if successful, otherwise false.</returns>
        /// <example>
        ///     Length.Parse("5.5 m", new CultureInfo("en-US"));
        /// </example>
        /// <param name="provider">Format to use when parsing number and unit. Defaults to <see cref="CultureInfo.CurrentUICulture" /> if null.</param>
        public static bool TryParse(string str, IFormatProvider provider, out Depth result)
        {
            return QuantityParser.Default.TryParse<Depth, DepthUnit>(
                str,
                provider,
                From,
                out result);
        }

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.ParseUnit("m", new CultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="UnitsNetException">Error parsing string.</exception>
        public static DepthUnit ParseUnit(string str)
        {
            return ParseUnit(str, null);
        }

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="provider">Format to use when parsing number and unit. Defaults to <see cref="CultureInfo.CurrentUICulture" /> if null.</param>
        /// <example>
        ///     Length.ParseUnit("m", new CultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="UnitsNetException">Error parsing string.</exception>
        public static DepthUnit ParseUnit(string str, IFormatProvider provider)
        {
            return UnitParser.Default.Parse<DepthUnit>(str, provider);
        }

        /// <inheritdoc cref="TryParseUnit(string,IFormatProvider,out UnitsNet.Units.DepthUnit)"/>
        public static bool TryParseUnit(string str, out DepthUnit unit)
        {
            return TryParseUnit(str, null, out unit);
        }

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="unit">The parsed unit if successful.</param>
        /// <returns>True if successful, otherwise false.</returns>
        /// <example>
        ///     Length.TryParseUnit("m", new CultureInfo("en-US"));
        /// </example>
        /// <param name="provider">Format to use when parsing number and unit. Defaults to <see cref="CultureInfo.CurrentUICulture" /> if null.</param>
        public static bool TryParseUnit(string str, IFormatProvider provider, out DepthUnit unit)
        {
            return UnitParser.Default.TryParse<DepthUnit>(str, provider, out unit);
        }

        #endregion

        #region Arithmetic Operators

        /// <summary>Negate the value.</summary>
        public static Depth operator -(Depth right)
        {
            return new Depth(-right.Value, right.Unit);
        }

        /// <summary>Get <see cref="Depth"/> from adding two <see cref="Depth"/>.</summary>
        public static Depth operator +(Depth left, Depth right)
        {
            return new Depth(left.Value + right.GetValueAs(left.Unit), left.Unit);
        }

        /// <summary>Get <see cref="Depth"/> from subtracting two <see cref="Depth"/>.</summary>
        public static Depth operator -(Depth left, Depth right)
        {
            return new Depth(left.Value - right.GetValueAs(left.Unit), left.Unit);
        }

        /// <summary>Get <see cref="Depth"/> from multiplying value and <see cref="Depth"/>.</summary>
        public static Depth operator *(double left, Depth right)
        {
            return new Depth(left * right.Value, right.Unit);
        }

        /// <summary>Get <see cref="Depth"/> from multiplying value and <see cref="Depth"/>.</summary>
        public static Depth operator *(Depth left, double right)
        {
            return new Depth(left.Value * right, left.Unit);
        }

        /// <summary>Get <see cref="Depth"/> from dividing <see cref="Depth"/> by value.</summary>
        public static Depth operator /(Depth left, double right)
        {
            return new Depth(left.Value / right, left.Unit);
        }

        /// <summary>Get ratio value from dividing <see cref="Depth"/> by <see cref="Depth"/>.</summary>
        public static double operator /(Depth left, Depth right)
        {
            return left.Meters / right.Meters;
        }

        #endregion

        #region Equality / IComparable

        /// <summary>Returns true if less or equal to.</summary>
        public static bool operator <=(Depth left, Depth right)
        {
            return left.Value <= right.GetValueAs(left.Unit);
        }

        /// <summary>Returns true if greater than or equal to.</summary>
        public static bool operator >=(Depth left, Depth right)
        {
            return left.Value >= right.GetValueAs(left.Unit);
        }

        /// <summary>Returns true if less than.</summary>
        public static bool operator <(Depth left, Depth right)
        {
            return left.Value < right.GetValueAs(left.Unit);
        }

        /// <summary>Returns true if greater than.</summary>
        public static bool operator >(Depth left, Depth right)
        {
            return left.Value > right.GetValueAs(left.Unit);
        }

        /// <summary>Returns true if exactly equal.</summary>
        /// <remarks>Consider using <see cref="Equals(Depth, double, ComparisonType)"/> for safely comparing floating point values.</remarks>
        public static bool operator ==(Depth left, Depth right)
        {
            return left.Equals(right);
        }

        /// <summary>Returns true if not exactly equal.</summary>
        /// <remarks>Consider using <see cref="Equals(Depth, double, ComparisonType)"/> for safely comparing floating point values.</remarks>
        public static bool operator !=(Depth left, Depth right)
        {
            return !(left == right);
        }

        /// <inheritdoc />
        public int CompareTo(object obj)
        {
            if(obj is null) throw new ArgumentNullException(nameof(obj));
            if(!(obj is Depth objDepth)) throw new ArgumentException("Expected type Depth.", nameof(obj));

            return CompareTo(objDepth);
        }

        /// <inheritdoc />
        public int CompareTo(Depth other)
        {
            return _value.CompareTo(other.GetValueAs(this.Unit));
        }

        /// <inheritdoc />
        /// <remarks>Consider using <see cref="Equals(Depth, double, ComparisonType)"/> for safely comparing floating point values.</remarks>
        public override bool Equals(object obj)
        {
            if(obj is null || !(obj is Depth objDepth))
                return false;

            return Equals(objDepth);
        }

        /// <inheritdoc />
        /// <remarks>Consider using <see cref="Equals(Depth, double, ComparisonType)"/> for safely comparing floating point values.</remarks>
        public bool Equals(Depth other)
        {
            return _value.Equals(other.GetValueAs(this.Unit));
        }

        /// <summary>
        ///     <para>
        ///     Compare equality to another Depth within the given absolute or relative tolerance.
        ///     </para>
        ///     <para>
        ///     Relative tolerance is defined as the maximum allowable absolute difference between this quantity's value and
        ///     <paramref name="other"/> as a percentage of this quantity's value. <paramref name="other"/> will be converted into
        ///     this quantity's unit for comparison. A relative tolerance of 0.01 means the absolute difference must be within +/- 1% of
        ///     this quantity's value to be considered equal.
        ///     <example>
        ///     In this example, the two quantities will be equal if the value of b is within +/- 1% of a (0.02m or 2cm).
        ///     <code>
        ///     var a = Length.FromMeters(2.0);
        ///     var b = Length.FromInches(50.0);
        ///     a.Equals(b, 0.01, ComparisonType.Relative);
        ///     </code>
        ///     </example>
        ///     </para>
        ///     <para>
        ///     Absolute tolerance is defined as the maximum allowable absolute difference between this quantity's value and
        ///     <paramref name="other"/> as a fixed number in this quantity's unit. <paramref name="other"/> will be converted into
        ///     this quantity's unit for comparison.
        ///     <example>
        ///     In this example, the two quantities will be equal if the value of b is within 0.01 of a (0.01m or 1cm).
        ///     <code>
        ///     var a = Length.FromMeters(2.0);
        ///     var b = Length.FromInches(50.0);
        ///     a.Equals(b, 0.01, ComparisonType.Absolute);
        ///     </code>
        ///     </example>
        ///     </para>
        ///     <para>
        ///     Note that it is advised against specifying zero difference, due to the nature
        ///     of floating point operations and using System.Double internally.
        ///     </para>
        /// </summary>
        /// <param name="other">The other quantity to compare to.</param>
        /// <param name="tolerance">The absolute or relative tolerance value. Must be greater than or equal to 0.</param>
        /// <param name="comparisonType">The comparison type: either relative or absolute.</param>
        /// <returns>True if the absolute difference between the two values is not greater than the specified relative or absolute tolerance.</returns>
        public bool Equals(Depth other, double tolerance, ComparisonType comparisonType)
        {
            if(tolerance < 0)
                throw new ArgumentOutOfRangeException("tolerance", "Tolerance must be greater than or equal to 0.");

            double thisValue = (double)this.Value;
            double otherValueInThisUnits = other.As(this.Unit);

            return UnitsNet.Comparison.Equals(thisValue, otherValueInThisUnits, tolerance, comparisonType);
        }

        /// <summary>
        ///     Returns the hash code for this instance.
        /// </summary>
        /// <returns>A hash code for the current Depth.</returns>
        public override int GetHashCode()
        {
            return new { Info.Name, Value, Unit }.GetHashCode();
        }

        #endregion

        #region Conversion Methods

        /// <summary>
        ///     Convert to the unit representation <paramref name="unit" />.
        /// </summary>
        /// <returns>Value converted to the specified unit.</returns>
        public double As(DepthUnit unit)
        {
            if(Unit == unit)
                return Convert.ToDouble(Value);

            var converted = GetValueAs(unit);
            return Convert.ToDouble(converted);
        }

        /// <inheritdoc cref="IQuantity.As(UnitSystem)"/>
        public double As(UnitSystem unitSystem)
        {
            if(unitSystem is null)
                throw new ArgumentNullException(nameof(unitSystem));

            var unitInfos = Info.GetUnitInfosFor(unitSystem.BaseUnits);

            var firstUnitInfo = unitInfos.FirstOrDefault();
            if(firstUnitInfo == null)
                throw new ArgumentException("No units were found for the given UnitSystem.", nameof(unitSystem));

            return As(firstUnitInfo.Value);
        }

        /// <inheritdoc />
        double IQuantity.As(Enum unit)
        {
            if(!(unit is DepthUnit unitAsDepthUnit))
                throw new ArgumentException($"The given unit is of type {unit.GetType()}. Only {typeof(DepthUnit)} is supported.", nameof(unit));

            return As(unitAsDepthUnit);
        }

        /// <summary>
        ///     Converts this Depth to another Depth with the unit representation <paramref name="unit" />.
        /// </summary>
        /// <returns>A Depth with the specified unit.</returns>
        public Depth ToUnit(DepthUnit unit)
        {
            var convertedValue = GetValueAs(unit);
            return new Depth(convertedValue, unit);
        }

        /// <inheritdoc />
        IQuantity IQuantity.ToUnit(Enum unit)
        {
            if(!(unit is DepthUnit unitAsDepthUnit))
                throw new ArgumentException($"The given unit is of type {unit.GetType()}. Only {typeof(DepthUnit)} is supported.", nameof(unit));

            return ToUnit(unitAsDepthUnit);
        }

        /// <inheritdoc cref="IQuantity.ToUnit(UnitSystem)"/>
        public Depth ToUnit(UnitSystem unitSystem)
        {
            if(unitSystem is null)
                throw new ArgumentNullException(nameof(unitSystem));

            var unitInfos = Info.GetUnitInfosFor(unitSystem.BaseUnits);

            var firstUnitInfo = unitInfos.FirstOrDefault();
            if(firstUnitInfo == null)
                throw new ArgumentException("No units were found for the given UnitSystem.", nameof(unitSystem));

            return ToUnit(firstUnitInfo.Value);
        }

        /// <inheritdoc />
        IQuantity IQuantity.ToUnit(UnitSystem unitSystem) => ToUnit(unitSystem);

        /// <inheritdoc />
        IQuantity<DepthUnit> IQuantity<DepthUnit>.ToUnit(DepthUnit unit) => ToUnit(unit);

        /// <inheritdoc />
        IQuantity<DepthUnit> IQuantity<DepthUnit>.ToUnit(UnitSystem unitSystem) => ToUnit(unitSystem);

        /// <summary>
        ///     Converts the current value + unit to the base unit.
        ///     This is typically the first step in converting from one unit to another.
        /// </summary>
        /// <returns>The value in the base unit representation.</returns>
        private double GetValueInBaseUnit()
        {
            switch(Unit)
            {
                case DepthUnit.Centimeter: return (_value) * 1e-2d;
                case DepthUnit.Decimeter: return (_value) * 1e-1d;
                case DepthUnit.Foot: return _value*0.3048;
                case DepthUnit.Hectometer: return (_value) * 1e2d;
                case DepthUnit.Inch: return _value*2.54e-2;
                case DepthUnit.Kilometer: return (_value) * 1e3d;
                case DepthUnit.Meter: return _value;
                case DepthUnit.Micrometer: return (_value) * 1e-6d;
                case DepthUnit.Mil: return _value*2.54e-5;
                case DepthUnit.Mile: return _value*1609.34;
                case DepthUnit.Millimeter: return (_value) * 1e-3d;
                case DepthUnit.Nanometer: return (_value) * 1e-9d;
                case DepthUnit.UsSurveyFoot: return _value*1200/3937;
                case DepthUnit.Yard: return _value*0.9144;
                default:
                    throw new NotImplementedException($"Can not convert {Unit} to base units.");
            }
        }

        /// <summary>
        ///     Converts the current value + unit to the base unit.
        ///     This is typically the first step in converting from one unit to another.
        /// </summary>
        /// <returns>The value in the base unit representation.</returns>
        internal Depth ToBaseUnit()
        {
            var baseUnitValue = GetValueInBaseUnit();
            return new Depth(baseUnitValue, BaseUnit);
        }

        private double GetValueAs(DepthUnit unit)
        {
            if(Unit == unit)
                return _value;

            var baseUnitValue = GetValueInBaseUnit();

            switch(unit)
            {
                case DepthUnit.Centimeter: return (baseUnitValue) / 1e-2d;
                case DepthUnit.Decimeter: return (baseUnitValue) / 1e-1d;
                case DepthUnit.Foot: return baseUnitValue/0.3048;
                case DepthUnit.Hectometer: return (baseUnitValue) / 1e2d;
                case DepthUnit.Inch: return baseUnitValue/2.54e-2;
                case DepthUnit.Kilometer: return (baseUnitValue) / 1e3d;
                case DepthUnit.Meter: return baseUnitValue;
                case DepthUnit.Micrometer: return (baseUnitValue) / 1e-6d;
                case DepthUnit.Mil: return baseUnitValue/2.54e-5;
                case DepthUnit.Mile: return baseUnitValue/1609.34;
                case DepthUnit.Millimeter: return (baseUnitValue) / 1e-3d;
                case DepthUnit.Nanometer: return (baseUnitValue) / 1e-9d;
                case DepthUnit.UsSurveyFoot: return baseUnitValue*3937/1200;
                case DepthUnit.Yard: return baseUnitValue/0.9144;
                default:
                    throw new NotImplementedException($"Can not convert {Unit} to {unit}.");
            }
        }

        #endregion

        #region ToString Methods

        /// <summary>
        ///     Gets the default string representation of value and unit.
        /// </summary>
        /// <returns>String representation.</returns>
        public override string ToString()
        {
            return ToString("g");
        }

        /// <summary>
        ///     Gets the default string representation of value and unit using the given format provider.
        /// </summary>
        /// <returns>String representation.</returns>
        /// <param name="provider">Format to use for localization and number formatting. Defaults to <see cref="CultureInfo.CurrentUICulture" /> if null.</param>
        public string ToString(IFormatProvider provider)
        {
            return ToString("g", provider);
        }

        /// <summary>
        ///     Get string representation of value and unit.
        /// </summary>
        /// <param name="significantDigitsAfterRadix">The number of significant digits after the radix point.</param>
        /// <returns>String representation.</returns>
        /// <param name="provider">Format to use for localization and number formatting. Defaults to <see cref="CultureInfo.CurrentUICulture" /> if null.</param>
        [Obsolete(@"This method is deprecated and will be removed at a future release. Please use ToString(""s2"") or ToString(""s2"", provider) where 2 is an example of the number passed to significantDigitsAfterRadix.")]
        public string ToString(IFormatProvider provider, int significantDigitsAfterRadix)
        {
            var value = Convert.ToDouble(Value);
            var format = UnitFormatter.GetFormat(value, significantDigitsAfterRadix);
            return ToString(provider, format);
        }

        /// <summary>
        ///     Get string representation of value and unit.
        /// </summary>
        /// <param name="format">String format to use. Default:  "{0:0.##} {1} for value and unit abbreviation respectively."</param>
        /// <param name="args">Arguments for string format. Value and unit are implicitly included as arguments 0 and 1.</param>
        /// <returns>String representation.</returns>
        /// <param name="provider">Format to use for localization and number formatting. Defaults to <see cref="CultureInfo.CurrentUICulture" /> if null.</param>
        [Obsolete("This method is deprecated and will be removed at a future release. Please use string.Format().")]
        public string ToString(IFormatProvider provider, [NotNull] string format, [NotNull] params object[] args)
        {
            if (format == null) throw new ArgumentNullException(nameof(format));
            if (args == null) throw new ArgumentNullException(nameof(args));

            provider = provider ?? CultureInfo.CurrentUICulture;

            var value = Convert.ToDouble(Value);
            var formatArgs = UnitFormatter.GetFormatArgs(Unit, value, provider, args);
            return string.Format(provider, format, formatArgs);
        }

        /// <inheritdoc cref="QuantityFormatter.Format{TUnitType}(IQuantity{TUnitType}, string, IFormatProvider)"/>
        /// <summary>
        /// Gets the string representation of this instance in the specified format string using <see cref="CultureInfo.CurrentUICulture" />.
        /// </summary>
        /// <param name="format">The format string.</param>
        /// <returns>The string representation.</returns>
        public string ToString(string format)
        {
            return ToString(format, CultureInfo.CurrentUICulture);
        }

        /// <inheritdoc cref="QuantityFormatter.Format{TUnitType}(IQuantity{TUnitType}, string, IFormatProvider)"/>
        /// <summary>
        /// Gets the string representation of this instance in the specified format string using the specified format provider, or <see cref="CultureInfo.CurrentUICulture" /> if null.
        /// </summary>
        /// <param name="format">The format string.</param>
        /// <param name="provider">Format to use for localization and number formatting. Defaults to <see cref="CultureInfo.CurrentUICulture" /> if null.</param>
        /// <returns>The string representation.</returns>
        public string ToString(string format, IFormatProvider provider)
        {
            return QuantityFormatter.Format<DepthUnit>(this, format, provider);
        }

        #endregion

        #region IConvertible Methods

        TypeCode IConvertible.GetTypeCode()
        {
            return TypeCode.Object;
        }

        bool IConvertible.ToBoolean(IFormatProvider provider)
        {
            throw new InvalidCastException($"Converting {typeof(Depth)} to bool is not supported.");
        }

        byte IConvertible.ToByte(IFormatProvider provider)
        {
            return Convert.ToByte(_value);
        }

        char IConvertible.ToChar(IFormatProvider provider)
        {
            throw new InvalidCastException($"Converting {typeof(Depth)} to char is not supported.");
        }

        DateTime IConvertible.ToDateTime(IFormatProvider provider)
        {
            throw new InvalidCastException($"Converting {typeof(Depth)} to DateTime is not supported.");
        }

        decimal IConvertible.ToDecimal(IFormatProvider provider)
        {
            return Convert.ToDecimal(_value);
        }

        double IConvertible.ToDouble(IFormatProvider provider)
        {
            return Convert.ToDouble(_value);
        }

        short IConvertible.ToInt16(IFormatProvider provider)
        {
            return Convert.ToInt16(_value);
        }

        int IConvertible.ToInt32(IFormatProvider provider)
        {
            return Convert.ToInt32(_value);
        }

        long IConvertible.ToInt64(IFormatProvider provider)
        {
            return Convert.ToInt64(_value);
        }

        sbyte IConvertible.ToSByte(IFormatProvider provider)
        {
            return Convert.ToSByte(_value);
        }

        float IConvertible.ToSingle(IFormatProvider provider)
        {
            return Convert.ToSingle(_value);
        }

        string IConvertible.ToString(IFormatProvider provider)
        {
            return ToString("g", provider);
        }

        object IConvertible.ToType(Type conversionType, IFormatProvider provider)
        {
            if(conversionType == typeof(Depth))
                return this;
            else if(conversionType == typeof(DepthUnit))
                return Unit;
            else if(conversionType == typeof(QuantityType))
                return Depth.QuantityType;
            else if(conversionType == typeof(QuantityInfo))
                return Depth.Info;
            else if(conversionType == typeof(BaseDimensions))
                return Depth.BaseDimensions;
            else
                throw new InvalidCastException($"Converting {typeof(Depth)} to {conversionType} is not supported.");
        }

        ushort IConvertible.ToUInt16(IFormatProvider provider)
        {
            return Convert.ToUInt16(_value);
        }

        uint IConvertible.ToUInt32(IFormatProvider provider)
        {
            return Convert.ToUInt32(_value);
        }

        ulong IConvertible.ToUInt64(IFormatProvider provider)
        {
            return Convert.ToUInt64(_value);
        }

        #endregion
    }
}
